config/routes.rb
InvestorRegister::Application.routes.draw do
  resources :companies

  resources :investors

  get "/user_session", :to=>"user_session#index", :as => "login"

  post "user_session", :to=>"user_session#create"

  resources :users do
    member do 
      get 'profile'
      get 'show_businesses'
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
 	belongs_to :user, class_name:'User'
  	attr_accessible :date, :members, :pitch_video, :stage, :vision
end

app/models/investor.rb
class Investor < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  attr_accessible :businesses_investedin, :income, :name, :past_experience, :type_of_investor
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :investors
  attr_accessible :name, :e_mail, :user_type, :password, :skype_username, :username

 validates_format_of :e_mail,:with=> /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :e_mail, :presence => true, 
   :uniqueness => true

 validates :password, :presence => true,
  :confirmation => true,
  :length => {:within => 6..40}

   validates :username, :presence => true,
  :length => {:within => 6..40},
  :uniqueness => true


  def authenticate(password)
  	self.password == password
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  # GET /investors
  # GET /investors.json
  def index
    @investors = Investor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @investors }
    end
  end

  # GET /investors/1
  # GET /investors/1.json
  def show
    @investor = Investor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @investor }
    end
  end

  # GET /investors/new
  # GET /investors/new.json
  def new
    @investor = Investor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @investor }
    end
  end

  # GET /investors/1/edit
  def edit
    @investor = Investor.find(params[:id])
  end

  # POST /investors
  # POST /investors.json
  def create
    @investor = Investor.new(params[:investor])
    @investor.user_id = session[:user].id

    respond_to do |format|
      if @investor.save
        format.html { redirect_to profile_user_path(@investor.user), notice: 'Investor was successfully created.' }
        format.json { render json: @investor, status: :created, location: @investor }
      else
        format.html { render action: "new" }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /investors/1
  # PUT /investors/1.json
  def update
    @investor = Investor.find(params[:id])

    respond_to do |format|
      if @investor.update_attributes(params[:investor])
        format.html { redirect_to profile_user_path(@investor.user), notice: 'Investor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1
  # DELETE /investors/1.json
  def destroy
    @investor = Investor.find(params[:id])
    @investor.destroy

    respond_to do |format|
      format.html { redirect_to investors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
  def index
  end

  def create
    # find the user with the email
  	user = User.where(e_mail: params[:e_mail].downcase).first

    if user && user.authenticate(params[:password])
      log_in user
  		redirect_to profile_user_path(user)
  	else
  		flash.now[:danger] = "Invaild email/password combination"
      render :index
  	end
  end

  def log_in(user)
    session[:user] = user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    # @users = @users.select{|x| x.username == params[:username]}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def show_businesses
        @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user]) 
    # verify email does not exist, if already exits, send error message back
    #if user != nil
    #  flash.now[:danger] = "email already exists"
    #  render :new
    # => else
      

    respond_to do |format|
      if @user.save 
        format.html {
          session[:user]
          redirect_to profile_user_path(@user), notice: 'User was successfully created.' 
        }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end 
    end 
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def profile
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vision %><br />
    <%= f.text_field :vision %>
  </div>
  <div class="field">
    <%= f.label :pitch_video %><br />
    <%= f.text_field :pitch_video %>
  </div>
  <div class="field">
    <%= f.label :stage %><br />
    <%= f.text_field :stage %>
  </div>
  <div class="field">
    <%= f.label :members %><br />
    <%= f.text_field :members %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Vision</th>
    <th>Pitch video</th>
    <th>Stage</th>
    <th>Members</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.vision %></td>
    <td><%= company.pitch_video %></td>
    <td><%= company.stage %></td>
    <td><%= company.members %></td>
    <td><%= company.date %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vision:</b>
  <%= @company.vision %>
</p>

<p>
  <b>Pitch video:</b>
  <%= @company.pitch_video %>
</p>

<p>
  <b>Stage:</b>
  <%= @company.stage %>
</p>

<p>
  <b>Members:</b>
  <%= @company.members %>
</p>

<p>
  <b>Date:</b>
  <%= @company.date %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/investors/_form.html.erb
<%= form_for(@investor) do |f| %>
  <% if @investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% @investor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :past_experience %><br />
    <%= f.text_field :past_experience %>
  </div>
  <div class="field">
    <%= f.label :businesses_investedin %><br />
    <%= f.text_field :businesses_investedin %>
  </div>
  <div class="field">
    <%= f.label :type_of_investor %><br />
    <%= f.text_field :type_of_investor %>
  </div>
  <div class="field">
    <%= f.label :income %><br />
    <%= f.number_field :income %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investors/edit.html.erb
<h1>Editing investor</h1>

<%= render 'form' %>

<%= link_to 'Show', @investor %> |
<%= link_to 'Back', investors_path %>

app/views/investors/index.html.erb
<h1>Listing investors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Past experience</th>
    <th>Businesses investedin</th>
    <th>Type of investor</th>
    <th>Income</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @investors.each do |investor| %>
  <tr>
    <td><%= investor.name %></td>
    <td><%= investor.past_experience %></td>
    <td><%= investor.businesses_investedin %></td>
    <td><%= investor.type_of_investor %></td>
    <td><%= investor.income %></td>
    <td><%= investor.user_id %></td>
    <td><%= link_to 'Show', investor %></td>
    <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
    <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Investor', new_investor_path %>

app/views/investors/new.html.erb
<h1>New investor</h1>

<%= render 'form' %>

<%= link_to 'Back', investors_path %>

app/views/investors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @investor.name %>
</p>

<p>
  <b>Past experience:</b>
  <%= @investor.past_experience %>
</p>

<p>
  <b>Businesses investedin:</b>
  <%= @investor.businesses_investedin %>
</p>

<p>
  <b>Type of investor:</b>
  <%= @investor.type_of_investor %>
</p>

<p>
  <b>Income:</b>
  <%= @investor.income %>
</p>


<%= link_to 'Edit', edit_investor_path(@investor) %> |
<%= link_to 'Back', investors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Venture</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/freelancer.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">Venture</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class ="page-scroll">
                    	<a href="/index.html">Home</a>
                    </li>	
                    <li class="page-scroll">
                        <a href="#/users/">Portfolio</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">About</a>
                    </li>
                    <li class="page-scroll">
                        <%= link_to "Login", login_path %>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <hr class=regular>
    <div class=newuser>
		<%= yield %>
	</div>
</body>
</html>

app/views/user_session/create.html.erb
<h1>UserSession#create</h1>
<p>Find me in app/views/user_session/create.html.erb</p>

app/views/user_session/index.html.erb
<div class=register_layout>	
<h1>Login Form</h1>
<%= flash.now[:danger] %>
<%= form_tag(login_path, :method=>"post") do %>
<span class=register_<%= label_tag :e_mail %>
<%= text_field_tag :e_mail %>
	
<%= label_tag :password %>
<%= text_field_tag :password %>

	<%= submit_tag "Login" %>
<% end %>
</div>
<p>register <%= link_to 'new', users_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div> 
  <div class="field">
      <%= f.label :password %><br />  
    <%= f.password_field :password%>
  <div class="field">
    <%= f.label :e_mail %><br />
    <%= f.text_field :e_mail %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.label :investor %><br />
    <%= f.select(:user_type, ["Investor", "Entrepreneur", "Both"]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
    <h1>Listing users</h1>
    <%= form_tag(users_path, :method=>"get") do %>
    <%= text_field_tag :username %><%= submit_tag "search" %>
    <% end %>
<table>     
  <tr>
    <th>Name</th>S
    <th>Username</th>
    
    <th>e_mail</th>
    <th>Skype username</th>
    <th>Investor entrepreneur</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    
    <td><%= user.e_mail %></td>
    <td><%= user.skype_username %></td>
    <td><%= user.investor_entrepreneur %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>            

<br />

<%= params %>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<%= link_to 'Edit', edit_user_path(@user)  if session[:user] == @user%> 
<% if @user.user_type == 'Investor' %>
Show Investor Stuff
<hr/>
<% @user.investors.each do |investor| %>
<block><%= investor.name %> </block>
<%= investor.past_experience %>
<% end %>
<hr/>
<%= link_to 'Edit your profile/portfolio', @user.investors.empty? ? new_investor_path : edit_investor_path(@user.investors.first) %>

<% elsif @user.user_type == 'Entrepreneur' %>
Show entrepreneur Stuff
<%= link_to 'Enter your business', new_company_path %>
<% else %>
Show both
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>e_mail:</b>
  <%= @user.e_mail %>
</p>

<p>
  <b>Investor entrepreneur:</b>
  <%= @user.investor_entrepreneur %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'My Account', edit_user_path %>

app/views/users/show_businesses.html.erb
<p>
  <b>Vision:</b>
  <%= @company.vision %>
</p>

<p>
  <b>Pitch video:</b>
  <%= @company.pitch_video %>
</p>

<p>
  <b>Stage:</b>
  <%= @company.stage %>
</p>

<p>
  <b>Members:</b>
  <%= @company.members %>
</p>

<p>
  <b>Date:</b>
  <%= @company.date %>
</p>